Upgrade ng 12
NewsWhip/style-guide pull request #180
Opened 2021-07-26 11:18 UTC by dinaNW

https://newswhip.atlassian.net/browse/RED-880
https://testspike3.gcp.newswhip.com/

2021-07-26 15:43 UTC, garethdn requested changes
CDK should definitely be upgraded - ngx-bootstrap probably should but it could be dependent on effort

2021-07-26 15:43 UTC, garethdn commented on package.json
>      "@angular/cdk": "^11.2.4",
This should probably go to v12

2021-07-26 15:43 UTC, garethdn commented on package.json
>      "ngx-bootstrap": "^6.2.0"
According to https://github.com/valor-software/ngx-bootstrap#compatibility we can and probably should move to v7 - but you should see what changes are in v7 to see if there's anything we need to update. This comment applies to Spike also. If you do update you'll need to update this reference in peerDependencies and the other in devDependencies

2021-07-27 15:21 UTC, dinaNW commented on src/_lib/sass/src/_feature-alerts.scss
> +        left: -#{$hotspot-size * 0.5};
Used https://sass-lang.com/documentation/cli/migrator for these.

2021-07-27 15:23 UTC, dinaNW commented on src/_lib/sass/styles.scss
> +@import "../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/hide-text";
Not sure what caused these paths to break, but simply saying `node_modules/...` no longer works.

2021-07-27 15:38 UTC, garethdn approved these changes

2021-08-03 12:59 UTC, merged